FROM rwd1/gui-l:latest
MAINTAINER RWd <rwd-github@gmx.net>

RUN apt-get update && apt-get upgrade -y \
	&& apt-get install -y \
	subversion \
	evolution \
	libreoffice \
	libreoffice-l10n-de \
	hunspell-de-de \
	gimp \
	gimp-help-de \
	zenity \
	vlc \
	rapidsvn \
	doublecmd-qt \
	x2goclient
